version: '3'

services:
  containo.services.orders.queueprocessor:
    image: tomkerkhove/containo.services.orders.queueprocessor
    build:
      context: .
      dockerfile: Containo.Services.Orders.QueueProcessor/Dockerfile

  containo.services.orders.api:
    image: tomkerkhove/containo.services.orders.api
    build:
      context: .
      dockerfile: Containo.Services.Orders.Api/Dockerfile


  containo.services.orders.validator:
    image: tomkerkhove/containo.services.orders.validator
    build:
      context: .
      dockerfile: ../Containo.Services.Orders.Validator/Dockerfile

